CREATE DATABASE IF NOT EXISTS assoc-life;
USE assoc-life;

CREATE TABLE IF NOT EXISTS Timestamps (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  create_time TIMESTAMP NOT NULL,
  update_time TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Template (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(30) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Menu (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(30) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Menus_Template (
    menu_id INT(6) UNSIGNED NOT NULL PRIMARY KEY,
    template_id INT(6) UNSIGNED NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS User (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(30) NOT NULL,
  lastname VARCHAR(30) NOT NULL,
  email VARCHAR(50)
);
